apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-deployment
spec:
  template:
    metadata:
      labels:
        app: gke-node-hello-world
    spec:
      containers:
      - name: my-container
        image: gcr.io/node-microservice-232714/gke-node-hello-world/image
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 3000
        env:
          - name: PROJECT_ID
            value: gke-node-hello-world
